-- COMERCIAL
INSERT INTO permisos (nombre, descripcion, esta_activo, created_at, updated_at, created_by, updated_by) VALUES
('VER CLIENTES',        'VER CLIENTES',        true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR CLIENTES',      'CREAR CLIENTES',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR CLIENTES',     'EDITAR CLIENTES',     true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR CLIENTES',   'ELIMINAR CLIENTES',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER VENTAS',          'VER VENTAS',          true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR VENTAS',        'CREAR VENTAS',        true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR VENTAS',       'EDITAR VENTAS',       true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR VENTAS',     'ELIMINAR VENTAS',     true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER COMPRAS',         'VER COMPRAS',         true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR COMPRAS',       'CREAR COMPRAS',       true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR COMPRAS',      'EDITAR COMPRAS',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR COMPRAS',    'ELIMINAR COMPRAS',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER INVENTARIO',      'VER INVENTARIO',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR INVENTARIO',    'CREAR INVENTARIO',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR INVENTARIO',   'EDITAR INVENTARIO',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR INVENTARIO', 'ELIMINAR INVENTARIO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER REPORTES COMERCIALES',      'VER REPORTES COMERCIALES',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR REPORTES COMERCIALES',    'CREAR REPORTES COMERCIALES',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR REPORTES COMERCIALES',   'EDITAR REPORTES COMERCIALES',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR REPORTES COMERCIALES', 'ELIMINAR REPORTES COMERCIALES', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);

-- FINANCIERO
INSERT INTO permisos (nombre, descripcion, esta_activo, created_at, updated_at, created_by, updated_by) VALUES
('VER CXC',         'VER CXC',         true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR CXC',       'CREAR CXC',       true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR CXC',      'EDITAR CXC',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR CXC',    'ELIMINAR CXC',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER CXP',         'VER CXP',         true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR CXP',       'CREAR CXP',       true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR CXP',      'EDITAR CXP',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR CXP',    'ELIMINAR CXP',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER MOVIMIENTOS',      'VER MOVIMIENTOS',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR MOVIMIENTOS',    'CREAR MOVIMIENTOS',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR MOVIMIENTOS',   'EDITAR MOVIMIENTOS',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR MOVIMIENTOS', 'ELIMINAR MOVIMIENTOS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER BANCOS',      'VER BANCOS',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR BANCOS',    'CREAR BANCOS',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR BANCOS',   'EDITAR BANCOS',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR BANCOS', 'ELIMINAR BANCOS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER REPORTES FINANCIEROS',      'VER REPORTES FINANCIEROS',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR REPORTES FINANCIEROS',    'CREAR REPORTES FINANCIEROS',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR REPORTES FINANCIEROS',   'EDITAR REPORTES FINANCIEROS',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR REPORTES FINANCIEROS', 'ELIMINAR REPORTES FINANCIEROS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);

-- USUARIOS
INSERT INTO permisos (nombre, descripcion, esta_activo, created_at, updated_at, created_by, updated_by) VALUES
('VER GESTIÓN USUARIOS',      'VER GESTIÓN USUARIOS',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR GESTIÓN USUARIOS',    'CREAR GESTIÓN USUARIOS',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR GESTIÓN USUARIOS',   'EDITAR GESTIÓN USUARIOS',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR GESTIÓN USUARIOS', 'ELIMINAR GESTIÓN USUARIOS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER ROLES Y PERMISOS',      'VER ROLES Y PERMISOS',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR ROLES Y PERMISOS',    'CREAR ROLES Y PERMISOS',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR ROLES Y PERMISOS',   'EDITAR ROLES Y PERMISOS',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR ROLES Y PERMISOS', 'ELIMINAR ROLES Y PERMISOS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),

('VER AUDITORÍA',      'VER AUDITORÍA',      true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('CREAR AUDITORÍA',    'CREAR AUDITORÍA',    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('EDITAR AUDITORÍA',   'EDITAR AUDITORÍA',   true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0),
('ELIMINAR AUDITORÍA', 'ELIMINAR AUDITORÍA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);
