package com.hersac.ui.globals.enums;

public enum Permiso {
    // COMERCIAL
    VER_CLIENTES(1),
    CREAR_CLIENTES(2),
    EDITAR_CLIENTES(3),
    ELIMINAR_CLIENTES(4),

    VER_VENTAS(5),
    CREAR_VENTAS(6),
    EDITAR_VENTAS(7),
    ELIMINAR_VENTAS(8),

    VER_COMPRAS(9),
    CREAR_COMPRAS(10),
    EDITAR_COMPRAS(11),
    ELIMINAR_COMPRAS(12),

    VER_INVENTARIO(13),
    CREAR_INVENTARIO(14),
    EDITAR_INVENTARIO(15),
    ELIMINAR_INVENTARIO(16),

    VER_REPORTE_COMERCIAL(17),
    CREAR_REPORTE_COMERCIAL(18),
    EDITAR_REPORTE_COMERCIAL(19),
    ELIMINAR_REPORTE_COMERCIAL(20),

    // FINANCIERO
    VER_CXC(21),
    CREAR_CXC(22),
    EDITAR_CXC(23),
    ELIMINAR_CXC(24),

    VER_CXP(25),
    CREAR_CXP(26),
    EDITAR_CXP(27),
    ELIMINAR_CXP(28),

    VER_MOVIMIENTOS(29),
    CREAR_MOVIMIENTOS(30),
    EDITAR_MOVIMIENTOS(31),
    ELIMINAR_MOVIMIENTOS(32),

    VER_BANCOS(33),
    CREAR_BANCOS(34),
    EDITAR_BANCOS(35),
    ELIMINAR_BANCOS(36),

    VER_REPORTE_FINANCIERO(37),
    CREAR_REPORTE_FINANCIERO(38),
    EDITAR_REPORTE_FINANCIERO(39),
    ELIMINAR_REPORTE_FINANCIERO(40),

    // USUARIOS
    VER_GESTION_USUARIO(41),
    CREAR_GESTION_USUARIO(42),
    EDITAR_GESTION_USUARIO(43),
    ELIMINAR_GESTION_USUARIO(44),

    VER_ROL_PERMISO(45),
    CREAR_ROL_PERMISO(46),
    EDITAR_ROL_PERMISO(47),
    ELIMINAR_ROL_PERMISO(48),

    VER_AUDITORIA(49),
    CREAR_AUDITORIA(50),
    EDITAR_AUDITORIA(51),
    ELIMINAR_AUDITORIA(52),

    // TERCEROS
    VER_TERCERO(53),
    CREAR_TERCERO(54),
    EDITAR_TERCERO(55),
    ELIMINAR_TERCERO(56);

    private final int id;

    Permiso(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }
}
